services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # SSL certificates (if using HTTPS)
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    env_file:
      - .env
    environment:
      # Override container-specific values
      - LANGUAGETOOL_URL=http://languagetool:8010
      # All other variables loaded from .env file
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-10485760}
      - PROCESSING_TIMEOUT=${PROCESSING_TIMEOUT:-300}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost,https://yourdomain.com}
      - PYTHONUNBUFFERED=1
      - DEBUG=${DEBUG:-false}
      - LOG_LEVEL=${LOG_LEVEL:-WARNING}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
      - DATABASE_URL=${DATABASE_URL:-}
      # LLM Configuration
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - LLM_ENHANCEMENT_ENABLED=${LLM_ENHANCEMENT_ENABLED:-false}
      - LLM_PROVIDER=${LLM_PROVIDER:-openai}
      - LLM_MODEL=${LLM_MODEL:-gpt-4o-mini}
      - LLM_REQUEST_TIMEOUT=${LLM_REQUEST_TIMEOUT:-30}
      - LLM_MAX_RETRIES=${LLM_MAX_RETRIES:-3}
      - LLM_RETRY_DELAY=${LLM_RETRY_DELAY:-1}
      - LLM_ENHANCE_ALL=${LLM_ENHANCE_ALL:-false}
    volumes:
      - backend_uploads:/app/uploads
      - backend_temp:/app/temp_files
    depends_on:
      languagetool:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
      args:
        # Frontend will call API via nginx at /api
        REACT_APP_API_URL: http://localhost/api
    environment:
      - NODE_ENV=production
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  languagetool:
    image: silviof/docker-languagetool:latest
    environment:
      - LANGUAGETOOL_OPTS=-Xmx2g
    volumes:
      - languagetool_data:/languagetool
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8010/v2/languages"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Optional: Redis for caching and session management
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  app-network:
    driver: bridge

volumes:
  backend_uploads:
  backend_temp:
  languagetool_data:
  redis_data:
