version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - LANGUAGETOOL_URL=http://languagetool:8081
      - MAX_FILE_SIZE=10485760
      - PROCESSING_TIMEOUT=300
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000
    volumes:
      - ./backend:/app
      - /app/venv
    depends_on:
      - languagetool
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  languagetool:
    image: silviof/docker-languagetool:latest
    ports:
      - "8081:8081"
    environment:
      - LANGUAGETOOL_OPTS=-Xmx2g
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  backend_venv:
  frontend_node_modules:
