services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Override container-specific values
      - LANGUAGETOOL_URL=http://languagetool:8010
      # All other variables loaded from .env file
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-10485760}
      - PROCESSING_TIMEOUT=${PROCESSING_TIMEOUT:-300}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000,http://frontend:3000}
      - PYTHONUNBUFFERED=1
      - DEBUG=${DEBUG:-true}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
      - DATABASE_URL=${DATABASE_URL:-}
      # LLM Configuration
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - LLM_ENHANCEMENT_ENABLED=${LLM_ENHANCEMENT_ENABLED:-false}
      - LLM_PROVIDER=${LLM_PROVIDER:-openai}
      - LLM_MODEL=${LLM_MODEL:-gpt-4o-mini}
      - LLM_REQUEST_TIMEOUT=${LLM_REQUEST_TIMEOUT:-30}
      - LLM_MAX_RETRIES=${LLM_MAX_RETRIES:-3}
      - LLM_RETRY_DELAY=${LLM_RETRY_DELAY:-1}
      - LLM_ENHANCE_ALL=${LLM_ENHANCE_ALL:-false}
    volumes:
      - ./backend:/app
      - backend_uploads:/app/uploads
      - backend_temp:/app/temp_files
    depends_on:
      - languagetool
    networks:
      - app-network
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
      args:
        # Frontend runs in browser, so it needs localhost (not backend hostname)
        REACT_APP_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  languagetool:
    image: silviof/docker-languagetool:latest
    ports:
      - "8081:8010"
    environment:
      - LANGUAGETOOL_OPTS=-Xmx2g
      - EXTRAOPTIONS=--host 0.0.0.0
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8010/v2/languages"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  app-network:
    driver: bridge

volumes:
  backend_uploads:
  backend_temp:
